name: Publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
permissions:
  contents: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: create
        name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: imgchop ${{ github.ref_name }}
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
  upload:
    name: Upload asset (${{ matrix.target.os }})
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - os: windows
            arch: amd64
            output: imgchop.exe
          - os: linux
            arch: amd64
            output: imgchop
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - run: go get .
      - id: version
        run: |
          version=$(echo ${{ github.ref_name }} | cut -dv -f2)
          echo "version=$version" >> $GITHUB_OUTPUT
      - run: go build -ldflags "-X main.version=${{ steps.version.outputs.version }}" -o "./build/${{ matrix.target.output }}"
        env:
          GOOS: ${{ matrix.target.os }}
          GOARCH: ${{ matrix.target.arch }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_name: ${{ matrix.target.output }}
          asset_path: ./build/${{ matrix.target.output }}
          asset_content_type: application/octet-stream
